name: 'AWS Secrets Manager Terraform Action'
author: 'Pedro Mello'
description: 'Use secrets from AWS Secrets Manager as Terraform environment variables in your GitHub Actions workflow'
inputs:
  aws-access-key-id:
    description: 'Access Key ID of the IAM user with the required AWS Secrets Manager permissions'
    required: true
  aws-secret-access-key:
    description: 'Corresponding Secret Access Key of the IAM user with the required AWS Secrets Manager permissions'
    required: true
  aws-region:
    description: 'The region of AWS Secrets Manager which contains your secrets (e.g.: us-east-1)'
    required: true
  secrets:
    description: 'List of secret names you want to fetch secret values for'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: lock
  color: blue
